title: 愛知県犬山市
description: 愛知県犬山市でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1Us-BEX8TvwLLmsjk49lfZO38Aqt_eilDDD12uufs57c/edit?usp=sharingexport?format=csv&gid=<:gid>
repository: https://github.com/iemeshi/app/
form_url: https://forms.gle/rD2Wd7bQogEcdc7FA
