title: 愛知県犬山市
description: 愛知県犬山市でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1Us-BEX8TvwLLmsjk49lfZO38Aqt_eilDDD12uufs57c/export?format=csv&gid=0
repository: https://github.com/ertama/inuyama.iemeshi.jp
form_url: https://forms.gle/rD2Wd7bQogEcdc7FA
